[supervisord]
nodaemon=false
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=warn

[program:dockerd]
command=dockerd --host=unix:///var/run/docker.sock --storage-driver=overlay2
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/dockerd.log
stderr_logfile=/var/log/supervisor/dockerd-error.log
priority=10
startsecs=3
